#!/bin/bash
#SBATCH -J real_rand_acc_pbcwb      # The job name
#SBATCH -o real_rand_acc_pbcwb.o%j     # output and error file name (%j expands to jobID)
#SBATCH -n 1            # number of MPI tasks (cores) requested
#SBATCH --ntasks-per-node=1  # task (cores) per node (maximum 24)
#SBATCH -p comp              # SLURM queue (partition)
echo $SLURM_JOB_ID
echo $SLURM_JOB_NAME
echo $SLURM_JOB_NUM_NODES

# Load your modules here
#module applications/anaconda3/4.0.0
#module load compilers/gcc/gnu/5.4.0
#module load tools/openmpi/gnu/1.8.4

# Run your task here
./bin/julio_demo_rand_acc_pbcwb